dbfilename redis_queue.rdb
dir /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/pids
pidfile /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/redis_queue.acl
