dbfilename redis_cache.rdb
dir /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/pids
pidfile /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13000
maxmemory 921mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /Users/vineethpakideri/Documents/erpnext/erp-projects/frappe-bench/config/redis_cache.acl
